CREATE TABLE enseignants(
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
	user_id INT UNIQUE,
    employeId VARCHAR(20) UNIQUE NOT NULL,
    dateEmbauche DATE NOT NULL,
    diplome VARCHAR(200),
    specialite VARCHAR(50),
    estProfesseurPrincipale BOOLEAN DEFAULT FALSE,
    dateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dateMiseAjour TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

